In [1]:

import numpy as np

# 200 stocks
stock_cnt = 200

#504 trade days
view_days = 504

# Normal distribution mean = 0, std = 1
stock_day_change = np.random.standard_normal((stock_cnt,
                                              view_days))

In [3]:

print(stock_day_change[0:2, 0:5])
stock_day_change[0:2, 0:5].astype(int)

[[ 0.901293   -0.01862414  0.09204024 -0.18621317 -0.54927495]
 [ 0.60266206 -1.02717357  0.76797468 -0.23567429 -0.70842047]]


array([[ 0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0]])

In [4]:

np.around(stock_day_change[0:2, 0:5], 2)

array([[ 0.9 , -0.02,  0.09, -0.19, -0.55],
       [ 0.6 , -1.03,  0.77, -0.24, -0.71]])

In [5]:

tmp_test = stock_day_change[0:2, 0:5].copy()

tmp_test[0][0] = np.nan
tmp_test

array([[        nan, -0.01862414,  0.09204024, -0.18621317, -0.54927495],
       [ 0.60266206, -1.02717357,  0.76797468, -0.23567429, -0.70842047]])

In [6]:

tmp_test = np.nan_to_num(tmp_test)
tmp_test

array([[ 0.        , -0.01862414,  0.09204024, -0.18621317, -0.54927495],
       [ 0.60266206, -1.02717357,  0.76797468, -0.23567429, -0.70842047]])