In [9]:

import numpy as np

# 100 0s
np.zeros(100)

# shape: 3 rows 2 columns of 0s
np.zeros((3,2))

# shape: 3 rows 3 columns of 1s
np.ones((3,2))

# shape: x=2, y=3, z=3
np.empty((2,3,3))

# Initialize shape like np_list, all 1s
np_list = np.ones(5) * 3
np.ones_like(np_list)

# Initialize shape like np_list, all 0s
np.zeros_like(np_list)

# eye() Unit Matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:

data = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]
]
arr_np = np.array(data)
arr_np


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:

np.linspace(0, 1, 10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:

# 200 stocks
stock_cnt = 200

#504 trade days
view_days = 504

# Generate a Array of Stocks and their changes. 
stock_day_change = np.random.standard_normal((stock_cnt,
                                              view_days)) 

# print shape(200, 504)
print(stock_day_change.shape)

# print first stock, first 5 days
print(stock_day_change[:1, :5])


(200, 504)
[[ 0.52772005 -1.23686502  0.51491667  0.18083315 -0.045416  ]]


In [13]:

np.save('./gen/stock_day_change', stock_day_change)
