In [1]:

import numpy as np

stock_day_change = np.load('./gen/stock_day_change.npy')


In [2]:

stock_day_change[:2, :5]


array([[ 0.52772005, -1.23686502,  0.51491667,  0.18083315, -0.045416  ],
       [ 1.32417809,  0.05159529, -1.02241279, -0.30628773, -1.52755081]])

In [2]:

stock_day_change[-2:, -5:]


array([[-1.03243722, -0.106677  , -1.54601428,  0.30439264,  0.16257845],
       [-1.02527985, -0.30049946, -1.12647611,  0.06621508, -0.71443007]])

In [4]:

temp = stock_day_change[0:2, 0:5].copy()

stock_day_change[0:2, 0:5] = stock_day_change[-2:, -5:]

stock_day_change[-2:, -5:] = temp

stock_day_change[0:2, 0:5], stock_day_change[-2:, -5:]

(array([[ 0.52772005, -1.23686502,  0.51491667,  0.18083315, -0.045416  ],
        [ 1.32417809,  0.05159529, -1.02241279, -0.30628773, -1.52755081]]),
 array([[ 1.33187212, -0.12179383, -0.75982958,  0.52701703, -0.40945897],
        [-0.741641  , -0.11308376,  0.10925913, -1.67585091, -0.62818711]]))