In [1]:

import numpy as np

# 200 stocks
stock_cnt = 200

#504 trade days
view_days = 504

# Normal distribution mean = 0, std = 1
stock_day_change = np.random.standard_normal((stock_cnt,
                                              view_days))

# print shape(200, 504)
print(stock_day_change.shape)

# print first stock, first 5 days
print(stock_day_change[0:1, :5])


(200, 504)
[[-0.34684593 -1.36306685 -0.71101589  0.04070414 -0.04369089]]


In [3]:

stock_day_change[0:2, 0:5]


array([[-1.1290258 ,  0.27532836, -0.65274524, -2.83417564,  0.31296201],
       [ 0.57936586, -1.48891826, -0.80046338,  0.66811418,  0.6898518 ]])

In [2]:

stock_day_change[-2:, -5:]


array([[-1.03243722, -0.106677  , -1.54601428,  0.30439264,  0.16257845],
       [-1.02527985, -0.30049946, -1.12647611,  0.06621508, -0.71443007]])

In [3]:

temp = stock_day_change[0:2, 0:5].copy()

stock_day_change[0:2, 0:5] = stock_day_change[-2:, -5:]

stock_day_change[-2:, -5:] = temp

stock_day_change[0:2, 0:5], stock_day_change[-2:, -5:]

(array([[-1.03243722, -0.106677  , -1.54601428,  0.30439264,  0.16257845],
        [-1.02527985, -0.30049946, -1.12647611,  0.06621508, -0.71443007]]),
 array([[-0.34684593, -1.36306685, -0.71101589,  0.04070414, -0.04369089],
        [ 0.82962663, -2.3186561 ,  0.8162474 ,  2.0840199 ,  0.35241981]]))