In [2]:

import numpy as np

stock_day_change = np.load('./gen/stock_day_change.npy')


In [3]:

print(stock_day_change[0:2, 0:5])
stock_day_change[0:2, 0:5].astype(int)


[[ 0.52772005 -1.23686502  0.51491667  0.18083315 -0.045416  ]
 [ 1.32417809  0.05159529 -1.02241279 -0.30628773 -1.52755081]]


array([[ 0, -1,  0,  0,  0],
       [ 1,  0, -1,  0, -1]])

In [4]:

np.around(stock_day_change[0:2, 0:5], 2)


array([[ 0.53, -1.24,  0.51,  0.18, -0.05],
       [ 1.32,  0.05, -1.02, -0.31, -1.53]])

In [5]:

tmp_test = stock_day_change[0:2, 0:5].copy()

tmp_test[0][0] = np.nan
tmp_test

array([[        nan, -1.23686502,  0.51491667,  0.18083315, -0.045416  ],
       [ 1.32417809,  0.05159529, -1.02241279, -0.30628773, -1.52755081]])

In [6]:

tmp_test = np.nan_to_num(tmp_test)
tmp_test

array([[ 0.        , -1.23686502,  0.51491667,  0.18083315, -0.045416  ],
       [ 1.32417809,  0.05159529, -1.02241279, -0.30628773, -1.52755081]])