In [3]:

import numpy as np

stock_day_change = np.load('./gen/stock_day_change.npy')


In [4]:

np.all(stock_day_change[0:2, 0:5] > 0)


False

In [5]:

np.any(stock_day_change[0:2, 0:5] > 0)


True

In [8]:

np.maximum(stock_day_change[0:2, 0:5], stock_day_change[-2:, -5:])


array([[ 1.33187212, -0.12179383,  0.51491667,  0.52701703, -0.045416  ],
       [ 1.32417809,  0.05159529,  0.10925913, -0.30628773, -0.62818711]])

In [9]:

change_int = stock_day_change[0:2, 0:5].astype(int)
print(change_int)

np.unique(change_int)

[[ 0 -1  0  0  0]
 [ 1  0 -1  0 -1]]


array([-1,  0,  1])

In [10]:

np.diff(stock_day_change[0:2, 0:5])


array([[-1.76458507,  1.75178169, -0.33408351, -0.22624915],
       [-1.27258281, -1.07400808,  0.71612507, -1.22126308]])

In [11]:

np.diff(stock_day_change[0:2, 0:5], axis=0)


array([[-0.69736965, -0.21785514, -0.12619308, -0.30485645,  0.76760641]])

In [11]:

tmp_test = stock_day_change[-2:, -5:]
print(np.where(tmp_test > 0.5, 1, 0))


[[1 0 0 1 0]
 [0 0 0 0 0]]


In [12]:

print(np.where(tmp_test > 0.5, 1, tmp_test))


[[ 1.         -0.12179383 -0.75982958  1.         -0.40945897]
 [-0.741641   -0.11308376  0.10925913 -1.67585091 -0.62818711]]


In [13]:

np.where(np.logical_or(tmp_test > 0.5, tmp_test < -0.5), 1, 0)

array([[1, 0, 1, 1, 0],
       [1, 0, 0, 1, 1]])