In [12]:

import numpy as np

# 200 stocks
stock_cnt = 200

#504 trade days
view_days = 504

# Normal distribution mean = 0, std = 1
stock_day_change = np.random.standard_normal((stock_cnt,
                                              view_days))

In [6]:
mask = stock_day_change[0:2, 0:5] > 0.5
print(mask)

[[False False  True False  True]
 [False False  True  True  True]]


In [7]:
tmp_test = stock_day_change[0:2, 0:5].copy()
tmp_test[mask]

array([1.39673744, 1.58281949, 1.07310878, 0.76476838, 0.98474692])

In [8]:

tmp_test[tmp_test > 0.5] = 1
tmp_test

array([[-2.09425282, -1.71558707,  1.        , -1.14516104,  1.        ],
       [-0.54089945, -0.3867708 ,  1.        ,  1.        ,  1.        ]])

In [15]:

tmp_test = stock_day_change[-2:, -5:]
print(tmp_test)
tmp_test | (tmp_test > 1) | (tmp_test < -1)

[[-1.47557655  0.04495852  0.74986596  0.75756249 -0.25519897]
 [ 1.23839248  0.04244041  1.28830107 -1.23496739  0.68378194]]


TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''