In [15]:

import numpy as np

stock_day_change = np.load('./gen/stock_day_change.npy')


In [16]:
mask = stock_day_change[0:2, 0:5] > 0.5
print(mask)


[[ True False  True False False]
 [ True False False False False]]


In [17]:
tmp_test = stock_day_change[0:2, 0:5].copy()
tmp_test[mask]


array([0.52772005, 0.51491667, 1.32417809])

In [18]:

tmp_test[tmp_test > 0.5] = 1
tmp_test

array([[ 1.        , -1.23686502,  1.        ,  0.18083315, -0.045416  ],
       [ 1.        ,  0.05159529, -1.02241279, -0.30628773, -1.52755081]])

In [20]:

tmp_test = stock_day_change[-2:, -5:]
print(tmp_test)
tmp_test[(tmp_test > 1) | (tmp_test < -1)]

[[ 1.33187212 -0.12179383 -0.75982958  0.52701703 -0.40945897]
 [-0.741641   -0.11308376  0.10925913 -1.67585091 -0.62818711]]


array([ 1.33187212, -1.67585091])