In [4]:

import numpy as np

# 200 stocks
stock_cnt = 200

#504 trade days
view_days = 504

# Normal distribution mean = 0, std = 1
stock_day_change = np.random.standard_normal((stock_cnt, view_days))


In [5]:

np.all(stock_day_change[0:2, 0:5] > 0)


False

In [6]:

np.any(stock_day_change[0:2, 0:5] > 0)


True

In [8]:

np.maximum(stock_day_change[0:2, 0:5], stock_day_change[-2:, -5:])


ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 

In [9]:

change_int = stock_day_change[0:2, 0:5].astype(int)
print(change_int)

np.unique(change_int)

[[0 0 0 0 0]
 [0 0 0 0 0]]


array([0])

In [10]:

np.diff(stock_day_change[0:2, 0:5])


array([[-0.74620536,  0.10997983,  0.42538259, -1.12313415],
       [-0.26669086,  0.20164189,  0.24671922, -0.05067129]])

In [11]:

np.diff(stock_day_change[0:2, 0:5], axis=0)


array([[-0.69736965, -0.21785514, -0.12619308, -0.30485645,  0.76760641]])

In [14]:

tmp_test = stock_day_change[-2:, -5:]
print(np.where(tmp_test > 0.5, 1, 0))


[['0' '0' 'Haha' '0' '0']
 ['Haha' 'Haha' '0' '0' '0']]


In [16]:

print(np.where(tmp_test > 0.5, 1, tmp_test))


[[-0.01864268 -0.66765041  1.         -0.76805078  0.26676159]
 [ 1.          1.         -0.30415205 -0.27642542 -0.98397264]]


In [17]:

np.where(np.logical_or(tmp_test > 0.5, tmp_test < -0.5), 1, 0)

array([[0, 1, 1, 1, 0],
       [1, 1, 0, 0, 1]])